# Generated by Django 5.0.2 on 2024-03-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.TextField(default='salt'),
            preserve_default=False,
        ),
    ]
